steps:
  # 1. COMPILAR EL PROYECTO Y CONSTRUIR LA IMAGEN DE DOCKER
  - name: gcr.io/cloud-builders/docker
    id: Build Biblioteca Image
    dir: Biblioteca # CRÍTICO: Asegura que se encuentre el Dockerfile y el código.
    args:
      [
        "build",
        "-t",
        "us-central1-docker.pkg.dev/practica2-477009/imagenes/biblioteca-service:latest",
        "."
      ]

  # 2. EMPUJAR LA IMAGEN AL ARTIFACT REGISTRY
  - name: gcr.io/cloud-builders/docker
    id: Push Biblioteca Image
    args:
      [
        "push",
        "us-central1-docker.pkg.dev/practica2-477009/imagenes/biblioteca-service:latest"
      ]

  # 3. DESPLEGAR EL SERVICIO EN CLOUD RUN (SIN INYECCIÓN DE VARIABLES)
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: Deploy Biblioteca to Cloud Run
    entrypoint: gcloud
    args:
      [
        "run", "deploy", "biblioteca-service",
        "--image=us-central1-docker.pkg.dev/practica2-477009/imagenes/biblioteca-service:latest",
        "--region=us-central1",
        "--platform=managed",
        "--allow-unauthenticated",
        "--timeout=300", # Mantenemos el timeout largo

        # CRÍTICO: SOLO DEJAMOS LA HABILITACIÓN DEL CLOUD SQL PROXY.
        # Ya no necesitamos --set-env-vars ni --update-secrets.
        "--add-cloudsql-instances", "practica2-477009:us-central1:id-postgres-bd"
      ]

images:
  - "us-central1-docker.pkg.dev/practica2-477009/imagenes/biblioteca-service:latest"

options:
  logging: CLOUD_LOGGING_ONLY