# 1. PUERTO OBLIGATORIO DE CLOUD RUN
server.port=${PORT:8080}

# 2. DATOS DE LA APLICACIÓN
spring.application.name=Biblioteca

# 3. CONFIGURACIÓN OPTIMIZADA DE CLOUD SQL CON EL STARTER DE GCP (POSTGRESQL)
# USANDO EL NOMBRE DE CONEXIÓN DEL PROYECTO NUEVO:
spring.cloud.gcp.sql.instance-connection-name=practica2-477009:us-central1:id-postgres-bd
spring.cloud.gcp.sql.database-name=${DB_NAME:library-db}

# 4. CREDENCIALES (Inyectadas como variables de entorno)
spring.datasource.username=${DB_USERNAME:user_default}
spring.datasource.password=${DB_PASSWORD:password_default}

# 5. DRIVER DE POSTGRESQL (CRÍTICO)
spring.datasource.driver-class-name=org.postgresql.Driver

# 6. JPA / Hibernate 
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# CRÍTICO: DIALECTO DE POSTGRESQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect