# 1. PUERTO OBLIGATORIO DE CLOUD RUN
server.port=${PORT:8080}

# 2. DATOS DE LA APLICACIÓN
spring.application.name=Biblioteca

# 3. CONEXIÓN TRADICIONAL POSTGRESQL (CRÍTICA Y RÁPIDA)
# Apunta al puerto local donde el Cloud SQL Proxy establece el túnel
spring.datasource.url=jdbc:postgresql://localhost:5432/biblioteca

# 4. CREDENCIALES (Inyectadas por Secret Manager o variables de entorno)
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# 5. DRIVER Y DIALECTO
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect